import { jsPDF } from "jspdf";

function cleanMarkdown(text = "") {
  return text
    .replace(/\*\*(.*?)\*\*/g, (_, p1) => p1.toUpperCase()) // bold
    .replace(/\*(.*?)\*/g, (_, p1) => p1)
    .replace(/#+\s?(.*)/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function exportChatToPdf(
  messages = [],
  filename = "Chat_Export.pdf",
  title = ""
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const margin = 50;
  const lineHeight = 18;
  const headerHeight = 56;
  const footerHeight = 40;
  const textWidth = pageWidth - margin * 2;
  let cursorY = margin + headerHeight;

  // ===== HEADER =====
  function addHeader() {
    const date = new Date().toLocaleString();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(34, 34, 34);
    doc.text(title, pageWidth / 2, margin + 16, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(110);
    doc.text(date, pageWidth - margin, margin + 16, { align: "right" });

    doc.setDrawColor(230);
    doc.setLineWidth(0.5);
    doc.line(margin, margin + 28, pageWidth - margin, margin + 28);
  }

  // ===== FOOTER =====
  function addFooters() {
    const total = doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(130);
      doc.text(`Page ${i} of ${total}`, pageWidth - margin, pageHeight - 25, {
        align: "right",
      });
      doc.text("Generated by Chatbot", margin, pageHeight - 25);
    }
  }

  // ===== PAGE BREAK HANDLER =====
  function checkPageSpace() {
    if (cursorY > pageHeight - margin - footerHeight) {
      doc.addPage();
      addHeader();
      // Reapply consistent font and text style
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(20);
      cursorY = margin + headerHeight;
    }
  }

  // ===== INITIALIZE =====
  addHeader();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(20);

  // ===== GROUP USER/ASSISTANT MESSAGES =====
  const pairs = [];
  let pendingUser = null;

  messages.forEach((m) => {
    const role = (m.role || "").toLowerCase();
    const content = cleanMarkdown(m.content || "");

    if (role === "user") {
      if (pendingUser) pairs.push({ user: pendingUser, assistant: null });
      pendingUser = content;
    } else if (role === "assistant") {
      if (pendingUser) {
        pairs.push({ user: pendingUser, assistant: content });
        pendingUser = null;
      } else pairs.push({ user: null, assistant: content });
    }
  });
  if (pendingUser) pairs.push({ user: pendingUser, assistant: null });

  // ===== DRAW CHAT CONTENT =====
  pairs.forEach((p) => {
    // --- USER ---
    if (p.user) {
      const userLines = doc.splitTextToSize(p.user, textWidth);
      checkPageSpace();

      // Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(17, 82, 147);
      doc.text("User:", margin, cursorY);
      cursorY += lineHeight;

      // Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(20);
      userLines.forEach((line) => {
        checkPageSpace();
        doc.text(line, margin + 20, cursorY);
        cursorY += lineHeight;
      });
      cursorY += 6;
    }

    // --- ASSISTANT ---
    if (p.assistant) {
      const assistantLines = doc.splitTextToSize(p.assistant, textWidth);
      checkPageSpace();

      // Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(0, 128, 0);
      doc.text("Assistant:", margin, cursorY);
      cursorY += lineHeight;

      // Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(20);
      assistantLines.forEach((line) => {
        checkPageSpace();
        doc.text(line, margin + 20, cursorY);
        cursorY += lineHeight;
      });
      cursorY += 10;
    }

    // Divider line
    checkPageSpace();
    doc.setDrawColor(220);
    doc.setLineWidth(0.4);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 12;
  });

  addFooters();
  doc.save(filename);
}
